/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User_Login_and_Registration;

import Admin_InterFace.Admin_Interface;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Niloy Sarker
 */
public class Admin_Login extends javax.swing.JFrame {

    public Admin_Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        UserLoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        Pasword = new javax.swing.JPasswordField();
        AdminLoginBtn = new javax.swing.JButton();
        UserBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setLayout(null);

        UserLoginPanel.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Login");

        jLabel2.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username : ");

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password : ");

        UserName.setBackground(new java.awt.Color(204, 255, 255));
        UserName.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        UserName.setForeground(new java.awt.Color(0, 0, 0));
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });

        Pasword.setBackground(new java.awt.Color(204, 255, 255));
        Pasword.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        Pasword.setForeground(new java.awt.Color(0, 0, 0));

        AdminLoginBtn.setBackground(new java.awt.Color(39, 56, 171));
        AdminLoginBtn.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        AdminLoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        AdminLoginBtn.setText("Login");
        AdminLoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserLoginPanelLayout = new javax.swing.GroupLayout(UserLoginPanel);
        UserLoginPanel.setLayout(UserLoginPanelLayout);
        UserLoginPanelLayout.setHorizontalGroup(
            UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLoginPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserLoginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLoginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasword, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        UserLoginPanelLayout.setVerticalGroup(
            UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLoginPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pasword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(AdminLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        MainPanel.add(UserLoginPanel);
        UserLoginPanel.setBounds(410, 160, 380, 400);

        UserBtn.setBackground(new java.awt.Color(39, 56, 171));
        UserBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        UserBtn.setForeground(new java.awt.Color(255, 255, 255));
        UserBtn.setText("User");
        UserBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserBtnActionPerformed(evt);
            }
        });
        MainPanel.add(UserBtn);
        UserBtn.setBounds(1020, 40, 60, 30);

        AdminBtn.setBackground(new java.awt.Color(39, 56, 171));
        AdminBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        AdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        AdminBtn.setText("Admin");
        AdminBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });
        MainPanel.add(AdminBtn);
        AdminBtn.setBounds(1090, 40, 60, 30);

        BackgroundLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        BackgroundLabel.setForeground(new java.awt.Color(0, 0, 0));
        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/smart-cities.jpg"))); // NOI18N
        BackgroundLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MainPanel.add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 0, 1180, 800);

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 800));

        setSize(new java.awt.Dimension(1194, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed

    }//GEN-LAST:event_AdminBtnActionPerformed

    private void UserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserBtnActionPerformed
        Login_and_Registration login_and_Registration = new Login_and_Registration();
        login_and_Registration.setVisible(true);
        login_and_Registration.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        login_and_Registration.setTitle("Smart City");
        login_and_Registration.pack();
        login_and_Registration.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_UserBtnActionPerformed

    private void AdminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginBtnActionPerformed
         String Username, Pass;
        try {
            if ("".equals(UserName.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "UserName is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(Pasword.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Username = UserName.getText();
                Pass = Pasword.getText();

                if ("admin".equals(Username) && "123456".equals(Pass)) {
                    Admin_Interface adminInterface = new Admin_Interface();
                    adminInterface.setVisible(true);
                    adminInterface.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                    adminInterface.setTitle("NS Bank");
                    adminInterface.pack();
                    adminInterface.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Incorrect Username or Password", "Error", JOptionPane.ERROR_MESSAGE);
                }

                Pasword.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AdminLoginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JButton AdminLoginBtn;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPasswordField Pasword;
    private javax.swing.JButton UserBtn;
    private javax.swing.JPanel UserLoginPanel;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
