/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User_Login_and_Registration;
import Jdbc_Connection.Dbconection;
import User_Interface.User_Interface;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author Niloy Sarker
 */
public class Login_and_Registration extends javax.swing.JFrame {

    public Login_and_Registration() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        UserLoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserNameFeild = new javax.swing.JTextField();
        PasswordFeild = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JButton();
        UserBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setLayout(null);

        UserLoginPanel.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username : ");

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password : ");

        UserNameFeild.setBackground(new java.awt.Color(204, 255, 255));
        UserNameFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserNameFeild.setForeground(new java.awt.Color(0, 0, 0));
        UserNameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFeildActionPerformed(evt);
            }
        });

        PasswordFeild.setBackground(new java.awt.Color(204, 255, 255));
        PasswordFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordFeild.setForeground(new java.awt.Color(0, 0, 0));

        LoginBtn.setBackground(new java.awt.Color(39, 56, 171));
        LoginBtn.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Harrington", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Don't have an account? ");

        RegisterBtn.setBackground(new java.awt.Color(39, 56, 171));
        RegisterBtn.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        RegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setText("Register Now");
        RegisterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterBtnMouseClicked(evt);
            }
        });
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserLoginPanelLayout = new javax.swing.GroupLayout(UserLoginPanel);
        UserLoginPanel.setLayout(UserLoginPanelLayout);
        UserLoginPanelLayout.setHorizontalGroup(
            UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLoginPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserLoginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserNameFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLoginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLoginPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserLoginPanelLayout.setVerticalGroup(
            UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLoginPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(UserLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterBtn))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        MainPanel.add(UserLoginPanel);
        UserLoginPanel.setBounds(410, 160, 380, 400);

        UserBtn.setBackground(new java.awt.Color(39, 56, 171));
        UserBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        UserBtn.setForeground(new java.awt.Color(255, 255, 255));
        UserBtn.setText("User");
        UserBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserBtnActionPerformed(evt);
            }
        });
        MainPanel.add(UserBtn);
        UserBtn.setBounds(1010, 40, 60, 30);

        AdminBtn.setBackground(new java.awt.Color(39, 56, 171));
        AdminBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        AdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        AdminBtn.setText("Admin");
        AdminBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });
        MainPanel.add(AdminBtn);
        AdminBtn.setBounds(1080, 40, 60, 30);

        BackgroundLabel.setBackground(new java.awt.Color(204, 255, 255));
        BackgroundLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BackgroundLabel.setForeground(new java.awt.Color(0, 0, 0));
        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/smart-cities.jpg"))); // NOI18N
        MainPanel.add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 0, 1180, 800);

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 800));

        setSize(new java.awt.Dimension(1194, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameFeildActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        RegistrationForm registrationPanel = new RegistrationForm();
        registrationPanel.setVisible(true);
        registrationPanel.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        registrationPanel.setTitle("Smart City");
        registrationPanel.pack();
        registrationPanel.setLocationRelativeTo(null);
        this.dispose();
          
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void RegisterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBtnMouseClicked
          
    }//GEN-LAST:event_RegisterBtnMouseClicked

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        Admin_Login admin_Login = new Admin_Login();
        admin_Login.setVisible(true);
        admin_Login.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        admin_Login.setTitle("Smart City");
        admin_Login.pack();
        admin_Login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_AdminBtnActionPerformed

    private void UserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
          String Username, Password, query, Passdb = null;
        int notfound = 0;
        try {
            Connection con = Dbconection.getConnection();
            Statement st = con.createStatement();
            if ("".equals(UserNameFeild.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(PasswordFeild.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                Username = UserNameFeild.getText();
                Password = PasswordFeild.getText();

                query = "SELECT * FROM user_info WHERE Username = '" + Username + "'";

                ResultSet rs = st.executeQuery(query);

                while (rs.next()) {
                    Passdb = rs.getString("Password");
                    notfound = 1;
                }

                if (notfound == 1 && Passdb.equals(Password)) {
                    User_Interface user_interface = new User_Interface(Username,Password);
                    user_interface.setVisible(true);
                    user_interface.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    user_interface.setTitle("Home");
                    user_interface.pack();
                    user_interface.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Incorrect username or password", "Error",
                            JOptionPane.ERROR_MESSAGE);
                }

                PasswordFeild.setText("");
            }
        } catch (Exception e) {
            System.out.println("Error!" + e.getMessage());
        }
    }//GEN-LAST:event_LoginBtnActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPasswordField PasswordFeild;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JButton UserBtn;
    private javax.swing.JPanel UserLoginPanel;
    private javax.swing.JTextField UserNameFeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
