/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User_Login_and_Registration;

import Jdbc_Connection.Dbconection;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Niloy Sarker
 */
public class RegistrationForm extends javax.swing.JFrame {

    String Path;
    File f;

    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrationFormPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AdressTextFeild = new javax.swing.JTextField();
        PassTextFeild = new javax.swing.JPasswordField();
        SubmitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Re_passTextFeild = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        MaleChkBox = new javax.swing.JRadioButton();
        FemaleChkBox = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        UserNameTextFeild = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        OcccupationTextFeild = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        BrouseBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CatagoryComboBox = new javax.swing.JComboBox<>();
        ClearBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrationFormPanel.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel2.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registration Form");

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username : ");

        jLabel4.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password : ");

        AdressTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        AdressTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdressTextFeild.setForeground(new java.awt.Color(0, 0, 0));
        AdressTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdressTextFeildActionPerformed(evt);
            }
        });

        PassTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        PassTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PassTextFeild.setForeground(new java.awt.Color(0, 0, 0));
        PassTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTextFeildActionPerformed(evt);
            }
        });

        SubmitBtn.setBackground(new java.awt.Color(39, 56, 171));
        SubmitBtn.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        SubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBtn.setText("Submit");
        SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Harrington", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Already have an account? ");

        jButton2.setBackground(new java.awt.Color(39, 56, 171));
        jButton2.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Re-type Pass :");

        Re_passTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        Re_passTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Re_passTextFeild.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender : ");

        MaleChkBox.setBackground(new java.awt.Color(255, 255, 255));
        MaleChkBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaleChkBox.setForeground(new java.awt.Color(0, 0, 0));
        MaleChkBox.setText("Male");
        MaleChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleChkBoxActionPerformed(evt);
            }
        });

        FemaleChkBox.setBackground(new java.awt.Color(255, 255, 255));
        FemaleChkBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FemaleChkBox.setForeground(new java.awt.Color(0, 0, 0));
        FemaleChkBox.setText("Female");
        FemaleChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleChkBoxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adress : ");

        UserNameTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        UserNameTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserNameTextFeild.setForeground(new java.awt.Color(0, 0, 0));
        UserNameTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextFeildActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Occupation : ");

        OcccupationTextFeild.setBackground(new java.awt.Color(255, 255, 255));
        OcccupationTextFeild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OcccupationTextFeild.setForeground(new java.awt.Color(0, 0, 0));
        OcccupationTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcccupationTextFeildActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Upload Your Image : ");

        imgLabel.setFont(new java.awt.Font("Harrington", 0, 14)); // NOI18N
        imgLabel.setForeground(new java.awt.Color(255, 255, 255));
        imgLabel.setText("Uplead Your  Image ");
        imgLabel.setAlignmentX(5.0F);
        imgLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BrouseBtn.setBackground(new java.awt.Color(153, 153, 153));
        BrouseBtn.setFont(new java.awt.Font("Harrington", 1, 16)); // NOI18N
        BrouseBtn.setForeground(new java.awt.Color(255, 255, 255));
        BrouseBtn.setText("Browse");
        BrouseBtn.setBorder(null);
        BrouseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrouseBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Catagory : ");

        CatagoryComboBox.setBackground(new java.awt.Color(255, 255, 255));
        CatagoryComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CatagoryComboBox.setForeground(new java.awt.Color(0, 0, 0));
        CatagoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Education", "HealthCare", "Buisness", "Transportation", "Administrative", "Other", " " }));

        ClearBtn.setBackground(new java.awt.Color(39, 56, 171));
        ClearBtn.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        ClearBtn.setText("Clear");
        ClearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistrationFormPanelLayout = new javax.swing.GroupLayout(RegistrationFormPanel);
        RegistrationFormPanel.setLayout(RegistrationFormPanelLayout);
        RegistrationFormPanelLayout.setHorizontalGroup(
            RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationFormPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationFormPanelLayout.createSequentialGroup()
                        .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameTextFeild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(OcccupationTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RegistrationFormPanelLayout.createSequentialGroup()
                                    .addComponent(MaleChkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(FemaleChkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Re_passTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AdressTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PassTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CatagoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrationFormPanelLayout.createSequentialGroup()
                                .addComponent(BrouseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RegistrationFormPanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrationFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationFormPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        RegistrationFormPanelLayout.setVerticalGroup(
            RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationFormPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Re_passTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FemaleChkBox)
                    .addComponent(MaleChkBox)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdressTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OcccupationTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CatagoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BrouseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClearBtn)
                    .addComponent(SubmitBtn))
                .addGap(40, 40, 40)
                .addGroup(RegistrationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(RegistrationFormPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 37, -1, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/smart-cities.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void AdressTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdressTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdressTextFeildActionPerformed

    private void PassTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassTextFeildActionPerformed

    private void MaleChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleChkBoxActionPerformed
        if (MaleChkBox.isSelected()) {
            FemaleChkBox.setSelected(false);
        }
    }//GEN-LAST:event_MaleChkBoxActionPerformed

    private void UserNameTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextFeildActionPerformed

    private void OcccupationTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcccupationTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OcccupationTextFeildActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        String Username, Password, Re_Password, Gender = "", Address, Occupation, Category;
        try {
            Connection con = Dbconection.getConnection();
            Statement st = con.createStatement();
            if (UserNameTextFeild.getText().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (PassTextFeild.getText().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (Re_passTextFeild.getText().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Re-Type-Password is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!MaleChkBox.isSelected() && !FemaleChkBox.isSelected()) {
                JOptionPane.showMessageDialog(new JFrame(), "Gender is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (AdressTextFeild.getText().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Address is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (OcccupationTextFeild.getText().isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Occupation is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (CatagoryComboBox.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(new JFrame(), "Category is required", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            Username = UserNameTextFeild.getText();
            Password = PassTextFeild.getText();
            Re_Password = Re_passTextFeild.getText();
            if (!Password.equals(Re_Password)) {
                JOptionPane.showMessageDialog(null, "Entered PIN does not match");
                return;
            }
            Gender = MaleChkBox.isSelected() ? "Male" : "Female";
            Address = AdressTextFeild.getText();
            Occupation = OcccupationTextFeild.getText();
            Category = (String) CatagoryComboBox.getSelectedItem();

            InputStream imgSelected = new FileInputStream(new File(Path));
             byte[] fileData = new byte[(int) f.length()];
            imgSelected.read(fileData);

            String query = "INSERT INTO user_info(Username,Password,Gender,Address,Occupation,Catagory,Profile_Pic)"
                    + "VALUES('" + Username + "', '" + Password + "' , '" + Gender + "' ,  '" + Address + "' , '" + Occupation + "' , '" + Category + "' , '" + imgSelected + "')";

            st.execute(query);

            UserNameTextFeild.setText("");
            PassTextFeild.setText("");
            Re_passTextFeild.setText("");
            MaleChkBox.setSelected(false);
            FemaleChkBox.setSelected(false);
            AdressTextFeild.setText("");
            OcccupationTextFeild.setText("");
            CatagoryComboBox.setSelectedIndex(-1);

            JOptionPane.showMessageDialog(null, "Account has been created successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void BrouseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrouseBtnActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(null);
         f = jf.getSelectedFile();
        Path = f.getAbsolutePath();
        try {
            BufferedImage bi = ImageIO.read(new File(Path));
            Image img = bi.getScaledInstance(135, 135, Image.SCALE_SMOOTH);
            ImageIcon ii = new ImageIcon(img);
            imgLabel.setText("");
            imgLabel.setIcon(ii);
        } catch (IOException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BrouseBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        UserNameTextFeild.setText("");
        PassTextFeild.setText("");
        Re_passTextFeild.setText("");
        AdressTextFeild.setText("");
        OcccupationTextFeild.setText("");
        CatagoryComboBox.setSelectedIndex(-1);
        imgLabel.setIcon(null);
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void FemaleChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleChkBoxActionPerformed
        if (FemaleChkBox.isSelected()) {
            MaleChkBox.setSelected(false);
        }
    }//GEN-LAST:event_FemaleChkBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login_and_Registration login_and_Registration = new Login_and_Registration();
        login_and_Registration.setVisible(true);
        login_and_Registration.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        login_and_Registration.setTitle("Smart City");
        login_and_Registration.pack();
        login_and_Registration.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdressTextFeild;
    private javax.swing.JButton BrouseBtn;
    private javax.swing.JComboBox<String> CatagoryComboBox;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JRadioButton FemaleChkBox;
    private javax.swing.JRadioButton MaleChkBox;
    private javax.swing.JTextField OcccupationTextFeild;
    private javax.swing.JPasswordField PassTextFeild;
    private javax.swing.JPasswordField Re_passTextFeild;
    private javax.swing.JPanel RegistrationFormPanel;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField UserNameTextFeild;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
