/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User_Interface;

import Jdbc_Connection.Dbconection;
import com.mysql.cj.jdbc.Blob;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Niloy Sarker
 */
public class FindYourPlacePanel extends javax.swing.JPanel {

    private JTable jTable1;
    private JLabel label;
    //private ShowRowDetails detailsFrame;

    public FindYourPlacePanel() {
        initComponents();
        initializeShowDetailsPanel();
        //detailsFrame = new ShowRowDetails(); 
    }

    private void initializeShowDetailsPanel() {

        ShowDetailsPanel.setLayout(new BorderLayout());

        label = new JLabel("");
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setForeground(Color.BLACK);
        label.setFont(new Font("Segoe UI", Font.BOLD, 36));
        label.setPreferredSize(new Dimension(100, 50));

        ShowDetailsPanel.add(label, BorderLayout.NORTH);

        jTable1 = new JTable();
        JScrollPane scrollPane = new JScrollPane(jTable1);

        scrollPane.setPreferredSize(new Dimension(620, 680));
        scrollPane.setSize(620, 700);

        // Add some padding around the scroll pane
        scrollPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        ShowDetailsPanel.add(scrollPane, BorderLayout.CENTER);

        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
    public void valueChanged(ListSelectionEvent event) {
        if (!event.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
            int selectedRow = jTable1.getSelectedRow();
            String placeName = (String) jTable1.getValueAt(selectedRow, 4);
            String district = (String) jTable1.getValueAt(selectedRow, 1);
            String upazila = (String) jTable1.getValueAt(selectedRow, 2);
            String category = (String) jTable1.getValueAt(selectedRow, 3);
            String location = (String) jTable1.getValueAt(selectedRow, 6);
            String details = (String) jTable1.getValueAt(selectedRow, 5);
            
            byte[] imageData = null;

            // Retrieve image data from the database
            try {
                Connection con = Dbconection.getConnection();
                Statement st = con.createStatement();
                String query = "SELECT Image FROM place_info WHERE AddPlace = ?";
                PreparedStatement pstmt = con.prepareStatement(query);
                pstmt.setString(1, placeName);
                ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    java.sql.Blob blob = rs.getBlob("Image");
                    if (blob != null) {
                        imageData = blob.getBytes(1, (int) blob.length());
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }

            ShowRowDetails detailsFrame = new ShowRowDetails(placeName, district, upazila, category, location, details, imageData);
            detailsFrame.setVisible(true);
        }
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        District = new javax.swing.JComboBox<>();
        Upazila = new javax.swing.JComboBox<>();
        Category = new javax.swing.JComboBox<>();
        SearchBtn = new javax.swing.JButton();
        ShowDetailsPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 0, 102));
        setPreferredSize(new java.awt.Dimension(960, 740));

        SearchPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Find Your Place");

        District.setBackground(new java.awt.Color(255, 255, 255));
        District.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        District.setForeground(new java.awt.Color(0, 0, 0));
        District.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selece Your Dristict", "Netrokona", " " }));

        Upazila.setBackground(new java.awt.Color(255, 255, 255));
        Upazila.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Upazila.setForeground(new java.awt.Color(0, 0, 0));
        Upazila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selece Your Upazila", "Netrokona Sadar", "Kendua", "Madan", "Atpara", "Khaliajuri", "Purbadhala", "Barhatta", "Durgapur", "Kalmakanda", "Mohonganj", " " }));

        Category.setBackground(new java.awt.Color(255, 255, 255));
        Category.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Category.setForeground(new java.awt.Color(0, 0, 0));
        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selece Category", "Education", "Healcare", "Buisness", "Tourist Spot", "Masque", "Tample", "ATM", " ", " ", " " }));

        SearchBtn.setBackground(new java.awt.Color(51, 51, 255));
        SearchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(255, 255, 255));
        SearchBtn.setText("Search");
        SearchBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(District, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Upazila, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(District, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Upazila, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(SearchBtn)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        ShowDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ShowDetailsPanelLayout = new javax.swing.GroupLayout(ShowDetailsPanel);
        ShowDetailsPanel.setLayout(ShowDetailsPanelLayout);
        ShowDetailsPanelLayout.setHorizontalGroup(
            ShowDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        ShowDetailsPanelLayout.setVerticalGroup(
            ShowDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ShowDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        String selectedDistrict = (String) District.getSelectedItem();
        String selectedUpazila = (String) Upazila.getSelectedItem();
        String selectedCategory = (String) Category.getSelectedItem();

        label.setText("Details");
        String query = "SELECT * FROM place_info WHERE District = '" + selectedDistrict
                + "' AND Upazila = '" + selectedUpazila
                + "' AND Category = '" + selectedCategory + "'";

        try {
            Connection con = Dbconection.getConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery(query);

            DefaultTableModel tblModel = new DefaultTableModel();
            jTable1.setModel(tblModel);
            tblModel.addColumn("SI_No");
            tblModel.addColumn("District");
            tblModel.addColumn("Upazila");
            tblModel.addColumn("Category");
            tblModel.addColumn("AddPlace");
            tblModel.addColumn("AddPlaceDetails");
            tblModel.addColumn("AddMapLink");
            tblModel.addColumn("Image");

            while (rs.next()) {
                Object[] rowData = new Object[8];
                rowData[0] = rs.getInt("SI_No");
                rowData[1] = rs.getString("District");
                rowData[2] = rs.getString("Upazila");
                rowData[3] = rs.getString("Category");
                rowData[4] = rs.getString("AddPlace");
                rowData[5] = rs.getString("AddPlaceDetails");
                rowData[6] = rs.getString("AddMapLink");
                rowData[7] = rs.getObject("Image"); // You may need to handle the image data appropriately
                tblModel.addRow(rowData);
            }

            con.close();

        } catch (Exception e) {
            System.out.println("Error!" + e.getMessage());
        }
    }//GEN-LAST:event_SearchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JComboBox<String> District;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JPanel ShowDetailsPanel;
    private javax.swing.JComboBox<String> Upazila;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
