/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User_Interface;

import Admin_InterFace.AddNewsPanel;
import Admin_InterFace.AddPlacePanel;
import User_Login_and_Registration.Admin_Login;
import java.awt.Color;

public class User_Interface extends javax.swing.JFrame {

    private final String Username; // Assuming you have a variable to store the account number
    private final String Password;

    private FindYourPlacePanel findYourPlacePanel;
    private final AddNewsPanel newsPAnel;

    public User_Interface(String Username, String Password) {
        initComponents();
        this.Username = Username;
        this.Password = Password;
        UserLabel.setText(Username);

        findYourPlacePanel = new FindYourPlacePanel();
        findYourPlacePanel.setVisible(false);

        getContentPane().add(findYourPlacePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 960, 740));

        newsPAnel = new AddNewsPanel();
        newsPAnel.setVisible(false);

        getContentPane().add(newsPAnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 960, 740));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        hmpgPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        findPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NewsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        HomePagePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(59, 70, 96));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/smart-city (2).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setText("I");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SMART CITY");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DASHBOARD");

        UserLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/male_user_50px.png"))); // NOI18N
        UserLabel.setText("   ");
        UserLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 769, Short.MAX_VALUE)
                .addComponent(UserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(UserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jPanel2.setBackground(new java.awt.Color(34, 38, 55));
        jPanel2.setLayout(null);

        hmpgPanel.setBackground(new java.awt.Color(137, 44, 161));
        hmpgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hmpgPanelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel1.setText("Homepage");

        javax.swing.GroupLayout hmpgPanelLayout = new javax.swing.GroupLayout(hmpgPanel);
        hmpgPanel.setLayout(hmpgPanelLayout);
        hmpgPanelLayout.setHorizontalGroup(
            hmpgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hmpgPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hmpgPanelLayout.setVerticalGroup(
            hmpgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hmpgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jPanel2.add(hmpgPanel);
        hmpgPanel.setBounds(0, 20, 230, 51);

        findPanel.setBackground(new java.awt.Color(34, 38, 55));
        findPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                findPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                findPanelMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8-place-26.png"))); // NOI18N
        jLabel2.setText("Find Your Place");

        javax.swing.GroupLayout findPanelLayout = new javax.swing.GroupLayout(findPanel);
        findPanel.setLayout(findPanelLayout);
        findPanelLayout.setHorizontalGroup(
            findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        findPanelLayout.setVerticalGroup(
            findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jPanel2.add(findPanel);
        findPanel.setBounds(0, 70, 230, 51);

        NewsPanel.setBackground(new java.awt.Color(34, 38, 55));
        NewsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewsPanelMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8-news-26.png"))); // NOI18N
        jLabel8.setText("News");

        javax.swing.GroupLayout NewsPanelLayout = new javax.swing.GroupLayout(NewsPanel);
        NewsPanel.setLayout(NewsPanelLayout);
        NewsPanelLayout.setHorizontalGroup(
            NewsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        NewsPanelLayout.setVerticalGroup(
            NewsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jPanel2.add(NewsPanel);
        NewsPanel.setBounds(0, 120, 230, 51);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 740));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/City Travel Vedio Intro Youtube (1).png"))); // NOI18N

        javax.swing.GroupLayout HomePagePanelLayout = new javax.swing.GroupLayout(HomePagePanel);
        HomePagePanel.setLayout(HomePagePanelLayout);
        HomePagePanelLayout.setHorizontalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );
        HomePagePanelLayout.setVerticalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(HomePagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 950, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPanelMouseClicked
        HomePagePanel.setVisible(false);
       newsPAnel.setVisible(false);
        findYourPlacePanel.setVisible(true);
    }//GEN-LAST:event_findPanelMouseClicked

    private void hmpgPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hmpgPanelMouseClicked
        HomePagePanel.setVisible(true);
        findYourPlacePanel.setVisible(false);
        newsPAnel.setVisible(false);
    }//GEN-LAST:event_hmpgPanelMouseClicked

    private void findPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPanelMouseEntered
        findPanel.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_findPanelMouseEntered

    private void findPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findPanelMouseExited
        findPanel.setBackground(new Color(34, 38, 55));
    }//GEN-LAST:event_findPanelMouseExited

    private void NewsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewsPanelMouseClicked
        HomePagePanel.setVisible(false);
        newsPAnel.setVisible(true);
        findYourPlacePanel.setVisible(false);
    }//GEN-LAST:event_NewsPanelMouseClicked

    private void NewsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewsPanelMouseEntered
        NewsPanel.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_NewsPanelMouseEntered

    private void NewsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewsPanelMouseExited
        NewsPanel.setBackground(new Color(34, 38, 55));
    }//GEN-LAST:event_NewsPanelMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JPanel NewsPanel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JPanel findPanel;
    private javax.swing.JPanel hmpgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
